version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14-alpine
    restart: always

    ports:
      - 8888:5432 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres321
      - POSTGRES_DB=test-db
    networks:
      - custom

networks:
  custom:
    driver: bridge